"use client";

import localFont from "next/font/local";
import "./globals.css";
import dynamic from "next/dynamic";
import { useEffect } from "react";
import Header from "@/components/Header";
import { NotificationProvider } from "web3uikit"
import { WagmiProvider } from "wagmi";
import config from "../components/wagmiConfig";


//apollo stuff
import { ApolloProvider,ApolloClient, InMemoryCache } from "@apollo/client";

const MoralisProvider = dynamic(() => import("react-moralis").then(mod => mod.MoralisProvider), { ssr: false });

//apollo stuff
const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: "https://api.studio.thegraph.com/query/91951/nft-marketplace/version/latest"
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    if (typeof window !== 'undefined') {
      console.log("Client-side render");
    }
  }, []);

  return (
    
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <WagmiProvider config={config}>
      <MoralisProvider initializeOnMount={false}>
        <ApolloProvider client={client}>
        <NotificationProvider>
        <Header/>
        {children}
        </NotificationProvider>
        </ApolloProvider>
      </MoralisProvider>
      </WagmiProvider>
    </body>
  </html>
  );
}
