"use client";

import localFont from "next/font/local";
import "./globals.css";
import dynamic from "next/dynamic";
import { useEffect } from "react";
import Header from "@/components/Header";

const MoralisProvider = dynamic(() => import("react-moralis").then(mod => mod.MoralisProvider), { ssr: false });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    if (typeof window !== 'undefined') {
      console.log("Client-side render");
    }
  }, []);

  return (
    
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <MoralisProvider initializeOnMount={false}>
        <Header/>
        {children}
      </MoralisProvider>
    </body>
  </html>
  );
}
//                yarn add moralis-v1 react-moralis ///////////////////////###############################
